language: android

android:
  components:
    - platform-tools
    - extra-android-m2repository
    - build-tools-27.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28

script:
  - ./gradlew assemble lint

  # This will run on Travis' 'new' container-based infrastructure
sudo: false

# Blacklist
branches:
  only:
    - master
 
env:
  global:
    # switch glibc to a memory conserving mode
    - MALLOC_ARENA_MAX=2
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10
    - GH_REPO_NAME: rdfproxy
    - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
    - GH_REPO_REF: github.com/situx/CuneiPainter.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x generateDocumentationAndDeploy.sh
  - ./generateDocumentationAndDeploy.sh
