language: android

android:
  components:
    - platform-tools
    - extra-android-m2repository
    - build-tools-27.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28

script:
  - ./gradlew assemble lint

  # This will run on Travis' 'new' container-based infrastructure
sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - cd docs
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
