CuneiPainter: StrokeType Enum Reference
StrokeType Enum Reference
Created by timo on 15.12.18 .
Public Member Functions
String toString ()
Public Attributes
A =("a")
B =("b")
C =("c")
D =("d")
E =("e")
F =("f")
INV_A =("!a")
INV_B =("!b")
String label
Private Member Functions
StrokeType (String label)
Detailed Description
Created by timo on 15.12.18 .
Constructor & Destructor Documentation
StrokeType (String label) private
{
         this.label=label;
     }
Member Function Documentation
String toString ()
{
         return this.label;
     }
Member Data Documentation
A =("a")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), LocationCalc.main(), DrawingCanvas.undoPath(), and DrawingCanvas.upTouch().
B =("b")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), LocationCalc.main(), DrawingCanvas.undoPath(), and DrawingCanvas.upTouch().
C =("c")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), DrawingCanvas.undoPath(), and DrawingCanvas.upTouch().
D =("d")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), DrawingCanvas.undoPath(), and DrawingCanvas.upTouch().
E =("e")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), and DrawingCanvas.upTouch().
F =("f")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), and DrawingCanvas.upTouch().
INV_A =("!a")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), and DrawingCanvas.upTouch().
INV_B =("!b")
Referenced by LocationCalc.calculateRelationBetweenTwoLines(), and DrawingCanvas.upTouch().
String label